# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.compute_value_api import ComputeValueApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComputeValueApi(unittest.TestCase):
    """ComputeValueApi unit test stubs"""

    def setUp(self):
        self.api = ComputeValueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_compute_value_all_index_get(self):
        """Test case for compute_value_all_index_get

        Obtain all compute value generated.  # noqa: E501
        """
        pass

    def test_compute_value_get_guid_get(self):
        """Test case for compute_value_get_guid_get

        Obtain the compute value specified.  # noqa: E501
        """
        pass

    def test_compute_value_last_compute_guid_get(self):
        """Test case for compute_value_last_compute_guid_get

        Obtain the last compute value of the compute in question.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
