# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_item_property_input_model import UpdateItemPropertyInputModel  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateItemPropertyInputModel(unittest.TestCase):
    """UpdateItemPropertyInputModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateItemPropertyInputModel(self):
        """Test UpdateItemPropertyInputModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_item_property_input_model.UpdateItemPropertyInputModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
