# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.request_api import RequestApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRequestApi(unittest.TestCase):
    """RequestApi unit test stubs"""

    def setUp(self):
        self.api = RequestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_request_all_get(self):
        """Test case for request_all_get

        Retrieves all requests owned by the stated user with a pagination of 100 items.  # noqa: E501
        """
        pass

    def test_request_create_post(self):
        """Test case for request_create_post

        Create a request.  # noqa: E501
        """
        pass

    def test_request_delete_guid_delete(self):
        """Test case for request_delete_guid_delete

        Delete a request.  # noqa: E501
        """
        pass

    def test_request_get_guid_get(self):
        """Test case for request_get_guid_get

        Retrieves the request with the mentioned guid.  # noqa: E501
        """
        pass

    def test_request_update_put(self):
        """Test case for request_update_put

        Update a request.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
