# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.component_historic_item_api import ComponentHistoricItemApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComponentHistoricItemApi(unittest.TestCase):
    """ComponentHistoricItemApi unit test stubs"""

    def setUp(self):
        self.api = ComponentHistoricItemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_component_historic_item_all_component_guid_get(self):
        """Test case for component_historic_item_all_component_guid_get

        Obtain all the component historical values created  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
