# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.component_api import ComponentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComponentApi(unittest.TestCase):
    """ComponentApi unit test stubs"""

    def setUp(self):
        self.api = ComponentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_component_all_get(self):
        """Test case for component_all_get

        Obtain all components you have created.  # noqa: E501
        """
        pass

    def test_component_create_post(self):
        """Test case for component_create_post

        Create a component.  # noqa: E501
        """
        pass

    def test_component_delete_delete(self):
        """Test case for component_delete_delete

        Delete a component.  # noqa: E501
        """
        pass

    def test_component_get_guid_get(self):
        """Test case for component_get_guid_get

        Obtain the component and its historical values.  # noqa: E501
        """
        pass

    def test_component_update_put(self):
        """Test case for component_update_put

        Update a component.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
