# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sub_compute_api import SubComputeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubComputeApi(unittest.TestCase):
    """SubComputeApi unit test stubs"""

    def setUp(self):
        self.api = SubComputeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sub_compute_all_by_child_child_compute_guid_get(self):
        """Test case for sub_compute_all_by_child_child_compute_guid_get

        Obtains all of the relevant parent computes the child compute has.  # noqa: E501
        """
        pass

    def test_sub_compute_all_by_parent_parent_compute_guid_get(self):
        """Test case for sub_compute_all_by_parent_parent_compute_guid_get

        Obtains all of the relevant child computes the parent compute has.  # noqa: E501
        """
        pass

    def test_sub_compute_all_index_get(self):
        """Test case for sub_compute_all_index_get

        Obtains all of the relevant Sub Computes you own.  # noqa: E501
        """
        pass

    def test_sub_compute_get_get(self):
        """Test case for sub_compute_get_get

        Obtains the specific sub compute.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
