# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.item_api import ItemApi  # noqa: E501
from swagger_client.rest import ApiException


class TestItemApi(unittest.TestCase):
    """ItemApi unit test stubs"""

    def setUp(self):
        self.api = ItemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_item_all_index_get(self):
        """Test case for item_all_index_get

        Obtains all of the relevant items you own.  # noqa: E501
        """
        pass

    def test_item_create_post(self):
        """Test case for item_create_post

        Create an item.  # noqa: E501
        """
        pass

    def test_item_exists_slug_get(self):
        """Test case for item_exists_slug_get

        Validates if the slug is being used.  # noqa: E501
        """
        pass

    def test_item_get_by_slug_slug_get(self):
        """Test case for item_get_by_slug_slug_get

        Obtains the specified item.  # noqa: E501
        """
        pass

    def test_item_get_item_guid_get(self):
        """Test case for item_get_item_guid_get

        Obtains the specified item.  # noqa: E501
        """
        pass

    def test_item_update_put(self):
        """Test case for item_update_put

        Update the specified item.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
