# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.component_type_api import ComponentTypeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComponentTypeApi(unittest.TestCase):
    """ComponentTypeApi unit test stubs"""

    def setUp(self):
        self.api = ComponentTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_component_type_all_get(self):
        """Test case for component_type_all_get

        Obtain all of the component types that are publicly available or the ones that you own.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
