# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.connect_api import ConnectApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConnectApi(unittest.TestCase):
    """ConnectApi unit test stubs"""

    def setUp(self):
        self.api = ConnectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connect_validate_head(self):
        """Test case for connect_validate_head

        Allows the client to validate his API key.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
