# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.websocket_command_property_view_model_i_collection_paginated_view_model import WebsocketCommandPropertyViewModelICollectionPaginatedViewModel  # noqa: E501
from swagger_client.rest import ApiException


class TestWebsocketCommandPropertyViewModelICollectionPaginatedViewModel(unittest.TestCase):
    """WebsocketCommandPropertyViewModelICollectionPaginatedViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebsocketCommandPropertyViewModelICollectionPaginatedViewModel(self):
        """Test WebsocketCommandPropertyViewModelICollectionPaginatedViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.websocket_command_property_view_model_i_collection_paginated_view_model.WebsocketCommandPropertyViewModelICollectionPaginatedViewModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
