# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.websocket_command_property_api import WebsocketCommandPropertyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWebsocketCommandPropertyApi(unittest.TestCase):
    """WebsocketCommandPropertyApi unit test stubs"""

    def setUp(self):
        self.api = WebsocketCommandPropertyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_websocket_command_property_all_by_command_get(self):
        """Test case for websocket_command_property_all_by_command_get

        Retrieves all websocket command properties relevant to its parent command.  # noqa: E501
        """
        pass

    def test_websocket_command_property_all_get(self):
        """Test case for websocket_command_property_all_get

        Retrieves all websocket command properties owned by the stated user with a pagination of  1000 items.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
