# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.compute_api import ComputeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComputeApi(unittest.TestCase):
    """ComputeApi unit test stubs"""

    def setUp(self):
        self.api = ComputeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_compute_all_index_get(self):
        """Test case for compute_all_index_get

        Obtains all of the relevant computes you own.  # noqa: E501
        """
        pass

    def test_compute_get_guid_get(self):
        """Test case for compute_get_guid_get

        Obtains the specific compute.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
