# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.websocket_command_property_view_model import WebsocketCommandPropertyViewModel  # noqa: E501
from swagger_client.rest import ApiException


class TestWebsocketCommandPropertyViewModel(unittest.TestCase):
    """WebsocketCommandPropertyViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebsocketCommandPropertyViewModel(self):
        """Test WebsocketCommandPropertyViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.websocket_command_property_view_model.WebsocketCommandPropertyViewModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
