# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComponentViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guid': 'str',
        'type': 'int',
        'value': 'str',
        'identifier': 'str',
        'query': 'str',
        'is_denominated': 'bool',
        'history': 'list[ComponentHistoricItemViewModel]'
    }

    attribute_map = {
        'guid': 'guid',
        'type': 'type',
        'value': 'value',
        'identifier': 'identifier',
        'query': 'query',
        'is_denominated': 'isDenominated',
        'history': 'history'
    }

    def __init__(self, guid=None, type=None, value=None, identifier=None, query=None, is_denominated=None, history=None):  # noqa: E501
        """ComponentViewModel - a model defined in Swagger"""  # noqa: E501
        self._guid = None
        self._type = None
        self._value = None
        self._identifier = None
        self._query = None
        self._is_denominated = None
        self._history = None
        self.discriminator = None
        if guid is not None:
            self.guid = guid
        if type is not None:
            self.type = type
        if value is not None:
            self.value = value
        if identifier is not None:
            self.identifier = identifier
        if query is not None:
            self.query = query
        if is_denominated is not None:
            self.is_denominated = is_denominated
        if history is not None:
            self.history = history

    @property
    def guid(self):
        """Gets the guid of this ComponentViewModel.  # noqa: E501


        :return: The guid of this ComponentViewModel.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this ComponentViewModel.


        :param guid: The guid of this ComponentViewModel.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def type(self):
        """Gets the type of this ComponentViewModel.  # noqa: E501


        :return: The type of this ComponentViewModel.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ComponentViewModel.


        :param type: The type of this ComponentViewModel.  # noqa: E501
        :type: int
        """

        self._type = type

    @property
    def value(self):
        """Gets the value of this ComponentViewModel.  # noqa: E501


        :return: The value of this ComponentViewModel.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ComponentViewModel.


        :param value: The value of this ComponentViewModel.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def identifier(self):
        """Gets the identifier of this ComponentViewModel.  # noqa: E501


        :return: The identifier of this ComponentViewModel.  # noqa: E501
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this ComponentViewModel.


        :param identifier: The identifier of this ComponentViewModel.  # noqa: E501
        :type: str
        """

        self._identifier = identifier

    @property
    def query(self):
        """Gets the query of this ComponentViewModel.  # noqa: E501


        :return: The query of this ComponentViewModel.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this ComponentViewModel.


        :param query: The query of this ComponentViewModel.  # noqa: E501
        :type: str
        """

        self._query = query

    @property
    def is_denominated(self):
        """Gets the is_denominated of this ComponentViewModel.  # noqa: E501


        :return: The is_denominated of this ComponentViewModel.  # noqa: E501
        :rtype: bool
        """
        return self._is_denominated

    @is_denominated.setter
    def is_denominated(self, is_denominated):
        """Sets the is_denominated of this ComponentViewModel.


        :param is_denominated: The is_denominated of this ComponentViewModel.  # noqa: E501
        :type: bool
        """

        self._is_denominated = is_denominated

    @property
    def history(self):
        """Gets the history of this ComponentViewModel.  # noqa: E501


        :return: The history of this ComponentViewModel.  # noqa: E501
        :rtype: list[ComponentHistoricItemViewModel]
        """
        return self._history

    @history.setter
    def history(self, history):
        """Sets the history of this ComponentViewModel.


        :param history: The history of this ComponentViewModel.  # noqa: E501
        :type: list[ComponentHistoricItemViewModel]
        """

        self._history = history

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComponentViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComponentViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
