# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComponentTypeViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'slug': 'str',
        'name': 'str',
        'description': 'str',
        'is_enabled': 'bool',
        'components': 'list[ComponentViewModel]'
    }

    attribute_map = {
        'id': 'id',
        'slug': 'slug',
        'name': 'name',
        'description': 'description',
        'is_enabled': 'isEnabled',
        'components': 'components'
    }

    def __init__(self, id=None, slug=None, name=None, description=None, is_enabled=None, components=None):  # noqa: E501
        """ComponentTypeViewModel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._slug = None
        self._name = None
        self._description = None
        self._is_enabled = None
        self._components = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if slug is not None:
            self.slug = slug
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if is_enabled is not None:
            self.is_enabled = is_enabled
        if components is not None:
            self.components = components

    @property
    def id(self):
        """Gets the id of this ComponentTypeViewModel.  # noqa: E501


        :return: The id of this ComponentTypeViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ComponentTypeViewModel.


        :param id: The id of this ComponentTypeViewModel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def slug(self):
        """Gets the slug of this ComponentTypeViewModel.  # noqa: E501


        :return: The slug of this ComponentTypeViewModel.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this ComponentTypeViewModel.


        :param slug: The slug of this ComponentTypeViewModel.  # noqa: E501
        :type: str
        """

        self._slug = slug

    @property
    def name(self):
        """Gets the name of this ComponentTypeViewModel.  # noqa: E501


        :return: The name of this ComponentTypeViewModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ComponentTypeViewModel.


        :param name: The name of this ComponentTypeViewModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this ComponentTypeViewModel.  # noqa: E501


        :return: The description of this ComponentTypeViewModel.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ComponentTypeViewModel.


        :param description: The description of this ComponentTypeViewModel.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def is_enabled(self):
        """Gets the is_enabled of this ComponentTypeViewModel.  # noqa: E501


        :return: The is_enabled of this ComponentTypeViewModel.  # noqa: E501
        :rtype: bool
        """
        return self._is_enabled

    @is_enabled.setter
    def is_enabled(self, is_enabled):
        """Sets the is_enabled of this ComponentTypeViewModel.


        :param is_enabled: The is_enabled of this ComponentTypeViewModel.  # noqa: E501
        :type: bool
        """

        self._is_enabled = is_enabled

    @property
    def components(self):
        """Gets the components of this ComponentTypeViewModel.  # noqa: E501


        :return: The components of this ComponentTypeViewModel.  # noqa: E501
        :rtype: list[ComponentViewModel]
        """
        return self._components

    @components.setter
    def components(self, components):
        """Sets the components of this ComponentTypeViewModel.


        :param components: The components of this ComponentTypeViewModel.  # noqa: E501
        :type: list[ComponentViewModel]
        """

        self._components = components

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComponentTypeViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComponentTypeViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
