# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ItemPropertyViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guid': 'str',
        'name': 'str',
        'value': 'str',
        'item_guid': 'str',
        'item': 'ItemViewModel'
    }

    attribute_map = {
        'guid': 'guid',
        'name': 'name',
        'value': 'value',
        'item_guid': 'itemGuid',
        'item': 'item'
    }

    def __init__(self, guid=None, name=None, value=None, item_guid=None, item=None):  # noqa: E501
        """ItemPropertyViewModel - a model defined in Swagger"""  # noqa: E501
        self._guid = None
        self._name = None
        self._value = None
        self._item_guid = None
        self._item = None
        self.discriminator = None
        if guid is not None:
            self.guid = guid
        if name is not None:
            self.name = name
        if value is not None:
            self.value = value
        if item_guid is not None:
            self.item_guid = item_guid
        if item is not None:
            self.item = item

    @property
    def guid(self):
        """Gets the guid of this ItemPropertyViewModel.  # noqa: E501


        :return: The guid of this ItemPropertyViewModel.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this ItemPropertyViewModel.


        :param guid: The guid of this ItemPropertyViewModel.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def name(self):
        """Gets the name of this ItemPropertyViewModel.  # noqa: E501


        :return: The name of this ItemPropertyViewModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ItemPropertyViewModel.


        :param name: The name of this ItemPropertyViewModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def value(self):
        """Gets the value of this ItemPropertyViewModel.  # noqa: E501


        :return: The value of this ItemPropertyViewModel.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ItemPropertyViewModel.


        :param value: The value of this ItemPropertyViewModel.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def item_guid(self):
        """Gets the item_guid of this ItemPropertyViewModel.  # noqa: E501


        :return: The item_guid of this ItemPropertyViewModel.  # noqa: E501
        :rtype: str
        """
        return self._item_guid

    @item_guid.setter
    def item_guid(self, item_guid):
        """Sets the item_guid of this ItemPropertyViewModel.


        :param item_guid: The item_guid of this ItemPropertyViewModel.  # noqa: E501
        :type: str
        """

        self._item_guid = item_guid

    @property
    def item(self):
        """Gets the item of this ItemPropertyViewModel.  # noqa: E501


        :return: The item of this ItemPropertyViewModel.  # noqa: E501
        :rtype: ItemViewModel
        """
        return self._item

    @item.setter
    def item(self, item):
        """Sets the item of this ItemPropertyViewModel.


        :param item: The item of this ItemPropertyViewModel.  # noqa: E501
        :type: ItemViewModel
        """

        self._item = item

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ItemPropertyViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemPropertyViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
