# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ItemViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guid': 'str',
        'logo_path': 'str',
        'abbreviation': 'str',
        'slug': 'str',
        'name': 'str',
        'denominations': 'int',
        'denomination_name': 'str',
        'parent_item_guid': 'str',
        'properties': 'list[ItemPropertyViewModel]',
        'types': 'list[TypeItemViewModel]',
        'requests': 'list[RequestViewModel]'
    }

    attribute_map = {
        'guid': 'guid',
        'logo_path': 'logoPath',
        'abbreviation': 'abbreviation',
        'slug': 'slug',
        'name': 'name',
        'denominations': 'denominations',
        'denomination_name': 'denominationName',
        'parent_item_guid': 'parentItemGuid',
        'properties': 'properties',
        'types': 'types',
        'requests': 'requests'
    }

    def __init__(self, guid=None, logo_path=None, abbreviation=None, slug=None, name=None, denominations=None, denomination_name=None, parent_item_guid=None, properties=None, types=None, requests=None):  # noqa: E501
        """ItemViewModel - a model defined in Swagger"""  # noqa: E501
        self._guid = None
        self._logo_path = None
        self._abbreviation = None
        self._slug = None
        self._name = None
        self._denominations = None
        self._denomination_name = None
        self._parent_item_guid = None
        self._properties = None
        self._types = None
        self._requests = None
        self.discriminator = None
        if guid is not None:
            self.guid = guid
        if logo_path is not None:
            self.logo_path = logo_path
        if abbreviation is not None:
            self.abbreviation = abbreviation
        if slug is not None:
            self.slug = slug
        if name is not None:
            self.name = name
        if denominations is not None:
            self.denominations = denominations
        if denomination_name is not None:
            self.denomination_name = denomination_name
        if parent_item_guid is not None:
            self.parent_item_guid = parent_item_guid
        if properties is not None:
            self.properties = properties
        if types is not None:
            self.types = types
        if requests is not None:
            self.requests = requests

    @property
    def guid(self):
        """Gets the guid of this ItemViewModel.  # noqa: E501


        :return: The guid of this ItemViewModel.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this ItemViewModel.


        :param guid: The guid of this ItemViewModel.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def logo_path(self):
        """Gets the logo_path of this ItemViewModel.  # noqa: E501


        :return: The logo_path of this ItemViewModel.  # noqa: E501
        :rtype: str
        """
        return self._logo_path

    @logo_path.setter
    def logo_path(self, logo_path):
        """Sets the logo_path of this ItemViewModel.


        :param logo_path: The logo_path of this ItemViewModel.  # noqa: E501
        :type: str
        """

        self._logo_path = logo_path

    @property
    def abbreviation(self):
        """Gets the abbreviation of this ItemViewModel.  # noqa: E501


        :return: The abbreviation of this ItemViewModel.  # noqa: E501
        :rtype: str
        """
        return self._abbreviation

    @abbreviation.setter
    def abbreviation(self, abbreviation):
        """Sets the abbreviation of this ItemViewModel.


        :param abbreviation: The abbreviation of this ItemViewModel.  # noqa: E501
        :type: str
        """

        self._abbreviation = abbreviation

    @property
    def slug(self):
        """Gets the slug of this ItemViewModel.  # noqa: E501


        :return: The slug of this ItemViewModel.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this ItemViewModel.


        :param slug: The slug of this ItemViewModel.  # noqa: E501
        :type: str
        """

        self._slug = slug

    @property
    def name(self):
        """Gets the name of this ItemViewModel.  # noqa: E501


        :return: The name of this ItemViewModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ItemViewModel.


        :param name: The name of this ItemViewModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def denominations(self):
        """Gets the denominations of this ItemViewModel.  # noqa: E501


        :return: The denominations of this ItemViewModel.  # noqa: E501
        :rtype: int
        """
        return self._denominations

    @denominations.setter
    def denominations(self, denominations):
        """Sets the denominations of this ItemViewModel.


        :param denominations: The denominations of this ItemViewModel.  # noqa: E501
        :type: int
        """

        self._denominations = denominations

    @property
    def denomination_name(self):
        """Gets the denomination_name of this ItemViewModel.  # noqa: E501


        :return: The denomination_name of this ItemViewModel.  # noqa: E501
        :rtype: str
        """
        return self._denomination_name

    @denomination_name.setter
    def denomination_name(self, denomination_name):
        """Sets the denomination_name of this ItemViewModel.


        :param denomination_name: The denomination_name of this ItemViewModel.  # noqa: E501
        :type: str
        """

        self._denomination_name = denomination_name

    @property
    def parent_item_guid(self):
        """Gets the parent_item_guid of this ItemViewModel.  # noqa: E501


        :return: The parent_item_guid of this ItemViewModel.  # noqa: E501
        :rtype: str
        """
        return self._parent_item_guid

    @parent_item_guid.setter
    def parent_item_guid(self, parent_item_guid):
        """Sets the parent_item_guid of this ItemViewModel.


        :param parent_item_guid: The parent_item_guid of this ItemViewModel.  # noqa: E501
        :type: str
        """

        self._parent_item_guid = parent_item_guid

    @property
    def properties(self):
        """Gets the properties of this ItemViewModel.  # noqa: E501


        :return: The properties of this ItemViewModel.  # noqa: E501
        :rtype: list[ItemPropertyViewModel]
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this ItemViewModel.


        :param properties: The properties of this ItemViewModel.  # noqa: E501
        :type: list[ItemPropertyViewModel]
        """

        self._properties = properties

    @property
    def types(self):
        """Gets the types of this ItemViewModel.  # noqa: E501


        :return: The types of this ItemViewModel.  # noqa: E501
        :rtype: list[TypeItemViewModel]
        """
        return self._types

    @types.setter
    def types(self, types):
        """Sets the types of this ItemViewModel.


        :param types: The types of this ItemViewModel.  # noqa: E501
        :type: list[TypeItemViewModel]
        """

        self._types = types

    @property
    def requests(self):
        """Gets the requests of this ItemViewModel.  # noqa: E501


        :return: The requests of this ItemViewModel.  # noqa: E501
        :rtype: list[RequestViewModel]
        """
        return self._requests

    @requests.setter
    def requests(self, requests):
        """Sets the requests of this ItemViewModel.


        :param requests: The requests of this ItemViewModel.  # noqa: E501
        :type: list[RequestViewModel]
        """

        self._requests = requests

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ItemViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
