# coding: utf-8

"""
    Nozomi API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateWebsocketCommandPropertyInputModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guid': 'str',
        'type': 'CommandPropertyType',
        'key': 'str',
        'value': 'str',
        'is_enabled': 'bool',
        'command_guid': 'str',
        'command_id': 'int',
        'id': 'int'
    }

    attribute_map = {
        'guid': 'guid',
        'type': 'type',
        'key': 'key',
        'value': 'value',
        'is_enabled': 'isEnabled',
        'command_guid': 'commandGuid',
        'command_id': 'commandId',
        'id': 'id'
    }

    def __init__(self, guid=None, type=None, key=None, value=None, is_enabled=None, command_guid=None, command_id=None, id=None):  # noqa: E501
        """UpdateWebsocketCommandPropertyInputModel - a model defined in Swagger"""  # noqa: E501
        self._guid = None
        self._type = None
        self._key = None
        self._value = None
        self._is_enabled = None
        self._command_guid = None
        self._command_id = None
        self._id = None
        self.discriminator = None
        if guid is not None:
            self.guid = guid
        if type is not None:
            self.type = type
        if key is not None:
            self.key = key
        if value is not None:
            self.value = value
        if is_enabled is not None:
            self.is_enabled = is_enabled
        if command_guid is not None:
            self.command_guid = command_guid
        if command_id is not None:
            self.command_id = command_id
        if id is not None:
            self.id = id

    @property
    def guid(self):
        """Gets the guid of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501


        :return: The guid of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this UpdateWebsocketCommandPropertyInputModel.


        :param guid: The guid of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :type: str
        """

        self._guid = guid

    @property
    def type(self):
        """Gets the type of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501


        :return: The type of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :rtype: CommandPropertyType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this UpdateWebsocketCommandPropertyInputModel.


        :param type: The type of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :type: CommandPropertyType
        """

        self._type = type

    @property
    def key(self):
        """Gets the key of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501


        :return: The key of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this UpdateWebsocketCommandPropertyInputModel.


        :param key: The key of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def value(self):
        """Gets the value of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501


        :return: The value of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this UpdateWebsocketCommandPropertyInputModel.


        :param value: The value of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def is_enabled(self):
        """Gets the is_enabled of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501


        :return: The is_enabled of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :rtype: bool
        """
        return self._is_enabled

    @is_enabled.setter
    def is_enabled(self, is_enabled):
        """Sets the is_enabled of this UpdateWebsocketCommandPropertyInputModel.


        :param is_enabled: The is_enabled of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :type: bool
        """

        self._is_enabled = is_enabled

    @property
    def command_guid(self):
        """Gets the command_guid of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501


        :return: The command_guid of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :rtype: str
        """
        return self._command_guid

    @command_guid.setter
    def command_guid(self, command_guid):
        """Sets the command_guid of this UpdateWebsocketCommandPropertyInputModel.


        :param command_guid: The command_guid of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :type: str
        """

        self._command_guid = command_guid

    @property
    def command_id(self):
        """Gets the command_id of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501


        :return: The command_id of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :rtype: int
        """
        return self._command_id

    @command_id.setter
    def command_id(self, command_id):
        """Sets the command_id of this UpdateWebsocketCommandPropertyInputModel.


        :param command_id: The command_id of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :type: int
        """

        self._command_id = command_id

    @property
    def id(self):
        """Gets the id of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501


        :return: The id of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UpdateWebsocketCommandPropertyInputModel.


        :param id: The id of this UpdateWebsocketCommandPropertyInputModel.  # noqa: E501
        :type: int
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateWebsocketCommandPropertyInputModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateWebsocketCommandPropertyInputModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
